### ISSUE TITLE
New MapReader class does not implement the retry of download of maps

### ISSUE THREAD

**Issue by aleberti** [astro-transients/tilepy#62]
The update introduced in #56 removed the feature where the skymap download is tried depending on the values of `downloadMaxRetry` and `downloadWaitPeriodRetry`. They are present in the "new" class `MapReaderLegacy`, but that class is not used anywhere.

**Comment by aleberti** [comment]
Mmmh it is correct, PR #63 indeed closed this issue. You can close it ;)
